// Pre-written country briefing notes in ADB economist style.
// Served statically — no AI API key required.

export const STATIC_BRIEFING_NOTES: Record<string, string> = {

PNG: `OVERVIEW OF THE ECONOMY & CURRENT DEVELOPMENTS

Papua New Guinea's economy expanded by an estimated 4.3% in 2024, driven by continued output growth at the ExxonMobil-operated PNG LNG facility in the Southern Highlands, rising gold and copper production at Lihir and Ok Tedi, and a partial resumption of operations at the Porgera gold mine following its reopening in 2023. Growth moderated from 5.2% in 2022 and 4.6% in 2023, reflecting softening global commodity prices and persistent foreign exchange (FX) shortages that constrained import-dependent sectors. The ADB projects real GDP growth of 4.1% in 2025 and 4.5% in 2026, underpinned by the ramp-up of the Papua LNG project — a second major LNG development led by TotalEnergies — and infrastructure investment in the Highlands Highway corridor.

Consumer price inflation, as measured by the PNG National Statistical Office CPI, peaked at 7.1% year-on-year (YOY) in 2022, driven by global food and fuel price shocks amplified by kina depreciation. Inflation moderated to 6.2% in 2023 and 5.6% in 2024, remaining above the Bank of Papua New Guinea (BPNG) informal target band of 3–5%. Food inflation, which carries a weight of approximately 42% in the CPI basket, eased to 6.1% YOY by end-2024 as global commodity prices stabilised, while transport and energy components remained elevated at 7.8% reflecting persistent fuel import costs. GDP per capita stood at approximately USD 2,880 in 2024, recovering toward but not yet reaching the pre-pandemic level of USD 2,950 recorded in 2019, with real per capita income growth constrained by a population growth rate of approximately 2.9% per annum.

The extractive sector — encompassing LNG, oil, gold, copper, and nickel — accounts for approximately 27% of GDP and 70% of export earnings, creating significant economic volatility tied to global commodity price cycles. Agriculture, forestry, and fishing contribute around 22% of GDP and support the livelihoods of an estimated 85% of the population through subsistence and smallholder activities in cocoa, coffee, copra, and palm oil. The services sector, concentrated in Port Moresby and Lae, contributes approximately 48% of GDP, with wholesale and retail trade, finance, and government services as the largest sub-components.

MONETARY POLICY & FINANCIAL SECTOR

The Bank of Papua New Guinea (BPNG) maintained the Kina Facility Rate (KFR) — its primary monetary policy instrument — at 3.0% throughout 2024 and into 2025, holding the rate unchanged since a 25 basis point cut in November 2020. BPNG's monetary stance is effectively constrained by the structural foreign exchange shortage, which limits the effectiveness of rate adjustments as a transmission mechanism. The central bank targets broad money growth and reserve money rather than a formal inflation target, reflecting the underdeveloped nature of domestic financial markets. The statutory reserve deposit (SRD) requirement has been maintained at 10% of eligible liabilities since 2022, providing a modest liquidity management tool.

Foreign exchange availability remained the defining constraint on monetary conditions in 2024. BPNG data indicate that unmet FX demand from the commercial banking system averaged approximately PGK 650 million per month in H1 2024, representing a structural shortage equivalent to around 8% of monthly import needs. The kina depreciated approximately 3.2% against the USD in 2024, trading at PGK 3.92–4.05/USD, with the official rate managed through periodic BPNG interventions. Private sector credit growth decelerated to 8.4% YOY by December 2024 from 11.2% in 2023, partly reflecting constraints on import financing. The banking system non-performing loan (NPL) ratio stood at approximately 5.4% at end-2024, elevated relative to the 3.8% pre-pandemic average.

Broad money supply (M3) growth moderated to 9.1% YOY in December 2024, equivalent to approximately 34% of GDP, compared with 12.6% in 2022. The deceleration reflected tighter reserve money conditions and slower government borrowing from the banking system. BSP Financial Group remains the dominant banking institution with approximately 45% of total banking system assets, followed by Kina Bank (21%), ANZ PNG (18%), and Westpac PNG (16%). The Average Weighted Lending Rate (AWLR) stood at 8.7% in Q3 2024, broadly unchanged since 2022 as competition in the commercial lending market remained limited.

FISCAL POLICY & PUBLIC DEBT

The central government fiscal deficit narrowed to an estimated 2.7% of GDP in 2024, from 3.4% in 2023 and a pandemic-period peak of 7.8% in 2020, reflecting stronger-than-expected LNG dividend revenues and improved tax compliance under the IRC's compliance improvement programme. The 2025 National Budget targets a further narrowing to 2.5% of GDP, with total revenue projected at PGK 24.8 billion (approximately 21.4% of GDP) and expenditure at PGK 27.8 billion. Resource revenue — comprising LNG project corporate income tax, dividends from the state-owned Kumul Petroleum Holdings, and mining royalties — accounted for approximately 31% of total revenue in 2024. Expenditure pressures remain concentrated in public sector wages and salaries (38% of recurrent expenditure), debt service (17%), and the infrastructure maintenance backlog, particularly on the Highlands Highway.

Total public debt stood at approximately 51% of GDP at end-2024, up from 30% in 2019 and a COVID-19 peak of 55% in 2021. External debt comprises approximately 62% of total debt, with multilateral creditors (World Bank 24%, ADB 19%, IMF 8%) and bilateral creditors (China Exim Bank 14%, Australia 7%) as the main lenders. Domestic debt (38% of total) is held primarily by commercial banks and the National Superannuation Fund (Nambawan Super). The IMF's 2024 Article IV assessment maintained PNG at moderate risk of debt distress under the baseline scenario, with risks rising to high under a commodity price shock. ADB's Public Financial Management programme, approved in 2023 with USD 100 million in budget support, includes conditionalities on revenue administration reform, SOE governance, and the Medium Term Fiscal Strategy.

BALANCE OF PAYMENTS

PNG's current account moved to a surplus of approximately 4.2% of GDP in 2024, the second consecutive year of surplus following the structural shift generated by LNG export ramp-up. LNG exports generated an estimated USD 5.8 billion in 2024, while gold and copper exports contributed USD 2.4 billion, together accounting for approximately 85% of total merchandise export earnings. The merchandise trade surplus was partially offset by a large services deficit driven by LNG project operator fees, insurance, and freight payments. Net FDI inflows declined to USD 420 million in 2024 from USD 680 million in 2023, reflecting a pause in Papua LNG project expenditure pending final investment decision.

Foreign exchange reserves held by BPNG stood at approximately USD 3.9 billion at end-2024, equivalent to 6.8 months of prospective import cover — above the 3-month adequacy threshold — but the usable reserve position, after netting out encumbered reserves and the BPNG's FX forward obligations, is estimated at approximately 4.1 months. Remittance inflows to PNG are modest relative to other Pacific economies, estimated at USD 24 million in 2024 (less than 0.1% of GDP), reflecting the limited stock of PNG workers in the formal diaspora compared with Melanesian neighbours.

OUTLOOK

PNG's medium-term growth outlook remains favourable at 4.0–5.5% per annum through 2027, anchored by LNG production stability and the eventual ramp-up of the Papua LNG project, which could add 1–2 percentage points to annual growth when it reaches full production. Key downside risks include: a sustained fall in global LNG or gold prices, which would compress resource revenues and widen the fiscal deficit; continued FX shortages constraining non-resource sector growth and import-dependent manufacturing; and governance risks including resource revenue management, which has historically limited the translation of mineral wealth into broad-based development outcomes. Inflation is expected to ease gradually toward 4.5% by end-2025 as global commodity price pressures moderate and kina depreciation stabilises.`,

FIJ: `OVERVIEW OF THE ECONOMY & CURRENT DEVELOPMENTS

Fiji's economy recorded estimated real GDP growth of 3.5% in 2024, consolidating the strong post-pandemic rebound of 19.8% in 2022 and 8.0% in 2023. The recovery was anchored by the tourism sector, which reached 961,000 visitor arrivals in the 12 months to September 2024 — surpassing the pre-pandemic peak of 894,000 recorded in 2019. Australia remained the largest source market at 41% of arrivals, followed by New Zealand (22%), the United States (14%), and other markets (23%). Tourism earnings are estimated at approximately FJD 2.1 billion in 2024, equivalent to 27% of GDP, with hotel occupancy averaging 72% nationally. The ADB projects continued growth of 3.8% in 2025 and 3.5% in 2026 as tourist arrivals approach the government's target of one million per year.

Consumer price inflation, as measured by the Fiji Bureau of Statistics (FBS) Fiji Consumer Price Index (FCPI), eased significantly from a peak of 6.1% YOY in 2022 to 4.2% in 2023 and 3.1% in 2024, reflecting lower global food and fuel prices and a stable Fiji dollar exchange rate. The food and non-alcoholic beverages component — weighted at 38% of the FCPI basket — eased to 2.8% YOY in Q3 2024, while housing, water, and electricity costs moderated to 3.4% following the Fiji Energy Authority's (FEA) tariff review. The Reserve Bank of Fiji (RBF) does not operate an explicit inflation target but monitors FCPI as a key input to monetary policy deliberations. GDP per capita stood at approximately USD 5,480 in 2024, exceeding the pre-pandemic level of USD 5,100 (2019) in nominal terms, although real per capita income recovery has been uneven, with informal sector workers and outer island communities benefiting less from the tourism-driven recovery.

Tourism, hospitality, and related services (transport, retail, finance) collectively account for approximately 40% of GDP and dominate formal employment. Sugar — cultivated by approximately 16,000 cane farmers on Viti Levu and Vanua Levu — contributes around 3% of GDP and 5% of export earnings, though the sector faces structural challenges including ageing mill infrastructure at the Fiji Sugar Corporation (FSC), declining cane yields, and competition from lower-cost producers. Gold mining at the Vatukoula Gold Mine contributes approximately 2% of GDP and remains an important employer in the Western Division. The financial services sector, concentrated in Suva, is the most developed in the Pacific, with BSP Fiji, ANZ Fiji, Westpac Fiji, and HFC Bank operating under RBF supervision.

MONETARY POLICY & FINANCIAL SECTOR

The Reserve Bank of Fiji (RBF) maintained the Overnight Policy Rate (OPR) at 0.25% throughout 2024 and into 2025, continuing the accommodative stance adopted in March 2020 in response to the COVID-19 pandemic. The RBF Board has signalled the OPR will remain at this level until credit growth is firmly established and the output gap closes fully. The Fijian dollar is pegged to a basket of currencies — comprising the Australian dollar, New Zealand dollar, US dollar, Japanese yen, and euro — managed through a fixed peg system that has remained stable since the 2009 devaluation. This exchange rate anchor limits the RBF's monetary policy autonomy but has provided nominal stability for trade and debt servicing.

Private sector credit growth accelerated to 9.2% YOY by December 2024, from 6.8% in 2023, driven by housing loans (up 11.3% YOY), personal loans (up 8.7%), and business credit in the tourism-related accommodation and food services sector (up 14.1%). The RBF's Business Confidence Survey (Q3 2024) showed the highest net positive sentiment since 2018 in the hotels and accommodation sub-sector. The banking system NPL ratio improved to 3.2% at end-2024 from a post-pandemic peak of 6.8% in 2021, reflecting loan restructuring completion and stronger tourism-sector cash flows. Total banking system assets stood at approximately FJD 8.4 billion at end-2024.

Broad money supply (M2) growth expanded to 7.8% YOY in December 2024 (approximately 73% of GDP), up from 5.2% in 2023, as private sector credit expanded and government deposits at the RBF declined. The Average Weighted Lending Rate (AWLR) edged up to 6.2% in Q3 2024 from 5.9% at end-2023, reflecting a gradual repricing of credit as legacy pandemic-era fixed-rate loans matured. The statutory reserve deposit requirement has remained at 5% since August 2020.

FISCAL POLICY & PUBLIC DEBT

Fiji's central government fiscal deficit narrowed to an estimated 3.8% of GDP in FY2024/25 (year ending July 2025), from 4.6% in FY2023/24 and a pandemic peak of 10.2% in FY2020/21. The FY2025/26 Budget, tabled in June 2025, targets a further consolidation to 3.2% of GDP, with revenue measures including a 2 percentage point increase in corporate income tax to 22%, a higher departure tax, and improved VAT compliance enforcement by the Fiji Revenue and Customs Service (FRCS). Total revenue is budgeted at FJD 3.82 billion (approximately 38% of GDP), with tax revenue comprising 74% of collections. Key expenditure pressures include the public sector wage bill (35% of recurrent expenditure), interest payments on public debt (estimated at 18% of revenue in FY2025/26), and post-Cyclone Winston infrastructure rehabilitation in the Northern and Eastern divisions.

Total public debt reached approximately FJD 8.1 billion (82% of GDP) at end-FY2024/25, elevated from 48% of GDP in FY2018/19 but declining from a peak of 91% in FY2021/22 as nominal GDP recovered. External debt comprises 54% of total (multilateral creditors: ADB 31%, World Bank 14%, bilateral creditors: India 9%), while domestic debt (46%) consists primarily of Fiji Government bonds held by the Fiji National Provident Fund (FNPF), commercial banks, and insurance companies. The IMF's 2024 Article IV consultation assessed Fiji at moderate risk of debt distress, noting that while the debt trajectory is declining, the pace of consolidation requires sustained primary surpluses. The government's Medium Term Fiscal Strategy (MTFS) 2024–2027 targets a return to primary surplus by FY2026/27 and public debt below 70% of GDP by 2030.

BALANCE OF PAYMENTS

Fiji's current account deficit narrowed to approximately 10.4% of GDP in 2024 from 13.6% in 2023, as tourism earnings recovered and the global energy price correction reduced the fuel import bill. Tourism receipts of approximately FJD 2.1 billion were the largest current account credit, offset by a merchandise trade deficit of approximately FJD 2.8 billion driven by fuel imports (FJD 620 million), machinery and equipment (FJD 480 million), and food (FJD 390 million). Remittance inflows reached FJD 1.02 billion in 2024 (approximately 13% of GDP), a 6.4% YOY increase, with Australia (38%), New Zealand (24%), and the United States (16%) as the principal sources.

Foreign reserves held at the RBF stood at FJD 3.18 billion at end-2024, equivalent to approximately 5.6 months of prospective import cover — comfortably above the RBF's 4-month adequacy threshold. The Fijian dollar remained stable against major trading partner currencies throughout 2024, with the peg basket managed without adjustment. FDI inflows of approximately FJD 420 million in 2024 were concentrated in the tourism sector (hotel expansion and renovation) and financial services, with Australian and New Zealand investors representing the largest source.

OUTLOOK

Fiji's economic outlook remains broadly positive, with growth projected at 3.5–4.0% through 2026 as tourism approaches full capacity utilisation and private investment in the accommodation sector continues. The primary downside risks are: a regional cyclone causing significant infrastructure damage and tourism disruption (Fiji's track record shows Category 3+ cyclone events approximately every 3–4 years); a global economic slowdown reducing Australian and New Zealand visitor demand; and fiscal slippage from the consolidation path if revenue shortfalls or election-cycle spending pressures emerge. Inflation is expected to remain in the 3.0–3.5% range through 2025–2026, contained by the exchange rate peg and moderating global commodity prices.`,

TON: `OVERVIEW OF THE ECONOMY & CURRENT DEVELOPMENTS

Tonga's economy is estimated to have grown 3.0% in FY2024/25 (year ending June 2025), the third consecutive year of positive growth following the severe economic disruption of the Hunga Tonga–Hunga Ha'apai volcanic eruption and tsunami in January 2022, which caused damage estimated at 18.5% of GDP. The recovery has been underpinned by reconstruction activity — largely financed by ADB, World Bank, and Australian government grants totalling approximately USD 150 million — strong remittance inflows from the Tongan diaspora in New Zealand, Australia, and the United States, and a partial recovery in tourism arrivals to approximately 45,000 in FY2024/25. The ADB projects growth of 2.8% in FY2025/26 and 3.2% in FY2026/27 as the reconstruction impulse fades and growth transitions toward remittance-supported consumption and small-scale service sector expansion.

Consumer price inflation, as measured by the Tonga Statistics Department CPI, reached a peak of 12.4% YOY in FY2021/22, driven by post-eruption supply disruptions, global food and fuel price shocks, and import-dependent price pressures in an economy where approximately 80% of consumer goods are imported. Inflation moderated sharply to 7.8% in FY2022/23, 5.1% in FY2023/24, and an estimated 4.2% in FY2024/25, as global commodity prices eased and supply chains normalised. The National Reserve Bank of Tonga (NRBT) does not operate a formal inflation target but monitors CPI as a key indicator alongside foreign reserve adequacy. GDP per capita stood at approximately USD 4,830 in 2024, recovering toward but remaining below the pre-eruption peak of USD 5,020 in FY2020/21 in nominal terms, with real incomes supported primarily by remittance receipts rather than domestic productivity growth.

Remittances are the dominant economic force in Tonga, equivalent to approximately 44% of GDP in FY2024/25 at TOP 558 million (approximately USD 234 million) — among the highest remittance-to-GDP ratios globally. The Pacific Australia Labour Mobility (PALM) Scheme has been transformative, with Tongan participants reaching 18,400 workers by 2025, up from 4,500 in 2019, earning Australian Award wages and remitting an estimated AUD 12,400 per worker per annum. Tourism and hospitality contribute approximately 8% of GDP in a normal year, though recovery to pre-pandemic levels (approximately 65,000 arrivals in 2018/19) has been gradual due to limited international flight capacity. Agriculture, fishing, and subsistence activities account for approximately 18% of GDP, with squash, vanilla, and root crops as primary export commodities.

MONETARY POLICY & FINANCIAL SECTOR

The National Reserve Bank of Tonga (NRBT) maintains monetary policy through reserve money management and the Minimum Lending Rate (MLR) rather than a conventional policy rate. The MLR has been held at 7.25% since March 2021 — unchanged through 2024 — as the NRBT sought to maintain accommodative credit conditions while monitoring external reserve adequacy. The Tongan pa'anga (TOP) is pegged to a basket of currencies dominated by the Australian dollar (AUD 55%), New Zealand dollar (NZD 25%), US dollar (USD 12%), and other currencies, providing exchange rate stability at the cost of independent monetary policy. Tonga's monetary policy transmission is limited by the shallow banking system, high lending margins, and the dominance of remittance income over bank credit as a source of household financing.

Private sector credit growth was subdued at 3.8% YOY in December 2024 from 5.2% in 2023, reflecting limited domestic investment opportunities and the preference of households to finance consumption through remittances rather than bank borrowing. The banking system is dominated by three commercial banks — ANZ Tonga, BSP Tonga, and MBf Bank — with total assets of approximately TOP 720 million. The system NPL ratio stood at 4.1% at end-2024, down from 6.8% post-eruption. Broad money supply (M2) growth was 6.2% YOY in December 2024 (approximately 68% of GDP), driven primarily by net foreign asset accumulation as remittance inflows exceeded import financing requirements.

The NRBT's foreign reserve position has been a key policy anchor, with reserves held at approximately USD 234 million at end-2024, equivalent to 7.2 months of import cover — well above the NRBT's 3-month minimum threshold. The high reserve buffer reflects the structural remittance surplus and has been supported by ADB, World Bank, and Australian budget support grants. Mobile money adoption has accelerated, with 71% of remittances received through MPaisa or TongaPay platforms in 2024 (up from 48% in 2022), reducing transaction costs from an average of 9.1% for bank transfers to approximately 4.2% for mobile money operators.

FISCAL POLICY & PUBLIC DEBT

The Tongan government's fiscal balance recorded an estimated deficit of 1.8% of GDP in FY2024/25, improved from 3.2% in FY2023/24 and a post-eruption peak of 8.6% in FY2021/22 when emergency reconstruction expenditures dominated the budget. Total revenue (including grants) is estimated at approximately TOP 580 million (44% of GDP), with tax revenue comprising 62% of collections, dominated by VAT (38% of tax revenue), customs and excise duties (31%), and income taxes (21%). External grants from Australia, New Zealand, ADB, and World Bank — totalling approximately TOP 120 million in FY2024/25 — remain a critical budget support, covering approximately 21% of total government expenditure. Expenditure pressures are concentrated in reconstruction-related capital spending (declining from the FY2022/23 peak), public sector wages and allowances (41% of recurrent expenditure), and rising debt service obligations.

Total public debt reached approximately 49% of GDP at end-FY2024/25, elevated from 31% in FY2018/19. External debt accounts for 78% of total, with the principal creditors being China Exim Bank (34% of external debt, primarily for road and telecommunications projects), ADB (28%), World Bank (19%), and bilateral creditors including Australia and New Zealand (14%). Concessional terms (grant element >35%) account for approximately 91% of the external debt stock. The IMF's March 2025 Debt Sustainability Analysis assessed Tonga at high risk of debt distress, driven primarily by the large stock of Chinese Exim Bank debt and vulnerability to external shocks. An ADB policy-based loan of USD 15 million approved in 2024 includes conditions on revenue mobilisation reform and the rationalisation of energy subsidies removed in January 2025, which had previously cost approximately 2.5% of GDP annually.

BALANCE OF PAYMENTS

Tonga's current account recorded an estimated surplus of 3.4% of GDP in FY2024/25, supported by remittances of TOP 558 million (44% of GDP) which more than offset the structural merchandise trade deficit of approximately 40% of GDP. Key imports include food (28% of import value), fuel (22%), and manufactured goods (31%), with a total import bill of approximately TOP 650 million. Tourism receipts are estimated at TOP 42 million in FY2024/25 (approximately 3% of GDP), recovering toward the pre-pandemic level of TOP 78 million in FY2018/19. Merchandise exports — primarily squash (TOP 18 million), root crops (TOP 8 million), and fish (TOP 6 million) — totalled approximately TOP 46 million, covering only 7% of import costs.

Foreign reserves of USD 234 million (7.2 months import cover) provide an adequate external buffer. The TOP/AUD exchange rate has remained broadly stable within the NRBT's managed peg band. FDI inflows are minimal at approximately USD 12 million per year, concentrated in hotel and resort development in Tongatapu and Vava'u.

OUTLOOK

Tonga's growth outlook is moderate at 2.5–3.5% per annum through FY2026/27, with remittances remaining the primary economic driver and reconstruction activity tapering. The key risks are: a severe cyclone causing repeat infrastructure damage and disrupting tourism (Tonga lies in the southwest Pacific cyclone belt); a reduction in PALM Scheme access due to Australian labour market policy changes, which would sharply reduce remittance inflows; rising debt service costs as the Chinese Exim Bank loan repayment schedule intensifies; and the long-run challenge of building a sustainable private sector economy beyond remittance-supported consumption. Inflation is expected to ease to 3.5–4.0% in FY2025/26 as global commodity price pressures moderate further.`,

SAM: `OVERVIEW OF THE ECONOMY & CURRENT DEVELOPMENTS

Samoa's economy grew at an estimated 4.8% in FY2024/25 (year ending June 2025), the strongest performance in six years, driven by a robust tourism recovery, sustained remittance inflows, and construction activity associated with public infrastructure investment. Tourist arrivals reached 183,000 in FY2024/25, a 28% YOY increase, supported by expanded Air New Zealand and Samoa Airways capacity, with total tourism receipts estimated at WST 420 million (approximately 16% of GDP). Remittances continued their upward trajectory, reaching WST 901 million (approximately 34% of GDP) in FY2024/25 — the single largest source of external income — driven by growth in Pacific Australia Labour Mobility (PALM) Scheme and Recognised Seasonal Employer (RSE) Scheme participation, with 14,200 Samoan workers in New Zealand and Australia. The ADB projects growth of 4.2% in FY2025/26 and 3.8% in FY2026/27 as the tourism recovery matures.

Consumer price inflation, as measured by the Samoa Bureau of Statistics (SBS) Consumer Price Index, moderated to 3.8% YOY in Q2 2025 from a peak of 10.9% in FY2021/22, driven by global food and fuel price shocks that pass through rapidly in a highly import-dependent economy (imports equivalent to approximately 55% of GDP). Inflation further eased from 6.4% in FY2022/23 and 4.9% in FY2023/24 as global commodity prices fell and the tala strengthened marginally against the USD. The food component (weighted at 41% of CPI) eased to 4.3% YOY in Q2 2025, while transport costs fell 1.2% reflecting lower fuel prices. GDP per capita stood at approximately USD 4,490 in 2024, surpassing the pre-pandemic level of USD 4,220 (FY2018/19), with the recovery disproportionately benefiting urban households in Apia and households with PALM/RSE income.

The Samoan economy is structurally anchored by three activity clusters: remittances and the diaspora economy (34% of GDP); tourism and hospitality (16% of GDP at current recovery levels, targeting 22% at full capacity); and the public sector including donor-financed government services (approximately 20% of GDP). Agriculture — dominated by taro, coconuts, cocoa, and subsistence cultivation — contributes approximately 10% of GDP and supports rural livelihoods. The fisheries sector, including both subsistence fishing and tuna processing at the Bluewave facility, generates approximately USD 18 million in export earnings. Samoa has no significant mineral resources, making it more reliant than PNG or Solomon Islands on service-sector and remittance-driven growth.

MONETARY POLICY & FINANCIAL SECTOR

The Central Bank of Samoa (CBS) maintained its Reference Interest Rate (RIR) at 7.75% throughout 2024 and into 2025, unchanged since a 50 basis point reduction in March 2021. The CBS monetary policy framework targets price stability and adequate international reserve levels, operating within the constraints of a managed exchange rate. The Samoan tala is pegged to a basket of currencies (Australian dollar 55%, US dollar 30%, New Zealand dollar 15%), a peg that has been maintained without realignment since 2011, providing an anchor for inflation expectations in the import-dominated economy.

Private sector credit growth recovered to 8.4% YOY by December 2024, from 4.1% in 2022 as post-pandemic business confidence improved, led by housing loans (up 12.1%), personal consumption credit (up 9.6%), and tourism-sector lending (up 14.3%). The commercial banking system — comprising ANZ Samoa, BSP Samoa, Samoa Commercial Bank, and National Bank of Samoa — held total assets of approximately WST 2.1 billion at end-2024, with an NPL ratio of 3.8%, down from a post-pandemic peak of 7.2% in 2021. The average lending rate across commercial banks stood at approximately 9.2% in Q3 2024, with deposit rates averaging 1.8%, reflecting wide interest margins that constrain financial inclusion.

Broad money supply (M2) growth was 9.1% YOY in December 2024 (approximately 62% of GDP), reflecting strong remittance inflows converted to tala deposits and growing private sector credit. The CBS held foreign reserves of approximately USD 326 million at end-2024, equivalent to 10.1 months of import cover — well above the CBS's 4-month threshold — providing a significant buffer against external shocks. The average cost of remittance transfers to Samoa fell to 6.9% in Q1 2025 from 8.2% in Q1 2023, reflecting increased competition from digital transfer operators including Western Union Digital and Wise, though still above the UN SDG target of 3%.

FISCAL POLICY & PUBLIC DEBT

Samoa's central government recorded an estimated fiscal deficit of 3.2% of GDP in FY2024/25, improved from 4.8% in FY2022/23 and a COVID-19 peak of 9.6% in FY2020/21. The FY2025/26 budget targets a deficit of 2.8% of GDP, with total revenue projected at WST 1.08 billion (41% of GDP), including tax revenue of WST 720 million and external grants of WST 240 million. The Value Added Goods and Services Tax (VAGST at 15%) is the largest single revenue source at 34% of tax collections, followed by income taxes (29%) and customs and excise (22%). Expenditure is dominated by education and health (combined 38% of recurrent expenditure), public sector wages (29%), and infrastructure maintenance. Donor grants — primarily from Australia, New Zealand, ADB, and the US Compact — finance approximately 22% of total government expenditure.

Public debt stood at approximately 52% of GDP at end-FY2024/25, declining from a peak of 58% in FY2021/22 and tracking toward the government's medium-term target of 50% of GDP by FY2027/28. External debt comprises approximately 74% of total, with ADB (38%), World Bank (24%), China Exim Bank (16%), and bilateral creditors (22%) as the main lenders. All external borrowing is on concessional terms. The IMF's 2024 DSA maintained Samoa at moderate risk of debt distress under the baseline, upgrading from high risk as the fiscal consolidation path improved post-pandemic. The CBS's Monetary Policy Statement (December 2024) noted that debt sustainability hinges critically on maintaining grant financing flows and avoiding large natural disaster reconstruction costs.

BALANCE OF PAYMENTS

Samoa's current account deficit narrowed to an estimated 5.1% of GDP in FY2024/25 from 8.4% in FY2022/23, as tourism receipts recovered and remittance inflows strengthened. The merchandise trade deficit of approximately 36% of GDP — driven by food imports (USD 95 million), fuel (USD 62 million), and machinery and transport equipment (USD 48 million) — was substantially offset by services exports (tourism receipts USD 152 million) and remittance transfers (USD 326 million, equivalent to 34% of GDP). Without remittances, the current account deficit would widen to approximately 22% of GDP, reflecting the economy's structural dependence on diaspora income flows.

Gross international reserves of USD 326 million (10.1 months import cover) are robust relative to Pacific SIDS peers and provide significant resilience. FDI inflows are modest at approximately USD 18 million per year, concentrated in tourism-related hotel development and financial services. The tala peg has remained stable and is expected to be maintained within the current basket arrangement.

OUTLOOK

Samoa's growth trajectory of 4.0–5.0% per annum through FY2026/27 is underpinned by continuing tourism recovery, sustained PALM/RSE remittance flows, and ADB-financed climate-resilient infrastructure. The primary downside risks are: a tropical cyclone causing tourism disruption and infrastructure damage (Samoa was severely affected by Cyclone Evan in 2012); a reduction in PALM Scheme access or remittance transfer volumes due to Australian policy changes; and a global economic slowdown reducing New Zealand and Australian visitor numbers. Inflation is projected to ease to 3.0–3.5% in FY2025/26 as global prices stabilise, remaining above the regional average but within manageable bounds.`,

SOL: `OVERVIEW OF THE ECONOMY & CURRENT DEVELOPMENTS

Solomon Islands' economy grew by an estimated 2.5% in 2024, a modest recovery from 3.2% in 2023, with growth constrained by persistent fiscal pressures, weakening global log prices — the dominant export commodity — and the aftermath of a 6.5-magnitude earthquake in Western Province in November 2023 that disrupted local production and damaged infrastructure. Growth was supported by construction activity related to the Pacific Games 2023 legacy infrastructure in Honiara, donor-financed public works programmes, and a gradual recovery in fishing sector revenues from the Exclusive Economic Zone (EEZ) tuna licensing. The ADB projects growth of 2.8% in 2025 and 3.5% in 2026, contingent on logging sector stabilisation and progress on structural reforms to diversify the economy.

Consumer price inflation, as measured by the Solomon Islands National Statistics Office (SINSO) CPI, stood at 6.1% YOY in Q2 2025, the highest in the Pacific subregion, reflecting imported food and fuel price pressures amplified by a narrow tradeable goods sector and limited domestic production capacity. Inflation eased from a peak of 8.3% in 2022 to 7.4% in 2023 and 6.4% in 2024, with food prices — weighted at 44% of the CPI basket — rising 7.9% YOY in Q2 2025 due to global rice and palm oil price increases. The Solomon Islands dollar (SBD) has experienced gradual depreciation against the USD, losing approximately 2.1% in 2024, contributing to imported inflation. GDP per capita was approximately USD 2,290 in 2024, among the lowest in the Pacific, with real per capita income growth constrained by a population growth rate of approximately 2.5% per annum.

Logging remains the dominant merchandise export, generating approximately USD 165 million in 2024 but representing a declining and unsustainable resource base as the primary forest stock is depleted. At current extraction rates — approximately 1.0–1.2 million cubic metres per annum — the commercially viable natural forest stock is estimated to be exhausted within 10–15 years, posing a fundamental structural challenge. Fisheries — through EEZ access licence fees and the SolTuna tuna cannery — generate approximately USD 45 million annually. Agriculture (copra, cocoa, palm oil) contributes approximately 25% of GDP through subsistence and smallholder activities. Tourism is nascent, with fewer than 30,000 arrivals annually, constrained by limited international air access to Henderson Airport and inadequate accommodation infrastructure.

MONETARY POLICY & FINANCIAL SECTOR

The Central Bank of Solomon Islands (CBSI) conducts monetary policy primarily through reserve money management and open market operations, rather than a conventional policy rate instrument. The CBSI Reference Rate has been maintained at 2.0% since 2020, reflecting accommodative conditions to support post-pandemic recovery. The Solomon Islands dollar is pegged to a currency basket (USD 50%, AUD 30%, NZD 10%, EUR 5%, JPY 5%), managed through periodic CBSI interventions in the interbank foreign exchange market. The shallow financial system — with only three commercial banks (BSP Solomon Islands, ANZ Solomon Islands, and Westpac Solomon Islands) and limited non-bank financial institutions — constrains monetary policy transmission.

Private sector credit growth was subdued at 4.2% YOY in December 2024, down from 6.1% in 2023, reflecting weak business confidence in non-resource sectors, high lending rates (average 10.8% in Q3 2024), and limited bankable investment opportunities. The NPL ratio stood at 5.8% at end-2024, elevated and reflective of the challenging operating environment for small and medium enterprises in Honiara and the provinces. CBSI foreign reserves declined to approximately USD 520 million at end-2024 (6.2 months import cover) from USD 590 million in 2023, as the merchandise trade deficit widened and EEZ fishing licence revenues were delayed. The CBSI maintains a minimum reserve adequacy threshold of 3 months of import cover.

FISCAL POLICY & PUBLIC DEBT

Solomon Islands recorded a fiscal deficit of an estimated 4.2% of GDP in 2024, widening from 2.8% in 2023, driven by post-Pacific Games capital expenditure carryovers, emergency earthquake response spending in Western Province, and revenue shortfalls from lower logging royalties reflecting weaker log export volumes and prices. Total revenue was approximately SBD 4.1 billion (27% of GDP), with tax revenue comprising 68% of collections and logging royalties a further 9%. Donor grants from Australia, New Zealand, the EU, and ADB financed approximately 18% of total government expenditure. Expenditure pressures are concentrated in public sector wages (42% of recurrent expenditure), goods and services, and rising infrastructure maintenance needs.

Public debt is relatively low at approximately 22% of GDP at end-2024 — the lowest among the Pacific SIDS assessed — but rising from 10% in 2019, driven by increased domestic borrowing (Solomon Islands Government bonds held by CBSI and commercial banks) and a modest draw on ADB and World Bank concessional facilities. The IMF's 2024 Article IV consultation assessed Solomon Islands at low-to-moderate risk of debt distress, with the primary vulnerability arising from the projected exhaustion of logging revenues and the need to finance a structural fiscal adjustment. A forthcoming ADB budget support loan of USD 20 million includes conditionalities on tax administration reform and the establishment of a sovereign wealth fund mechanism to manage the transition away from logging revenues.

BALANCE OF PAYMENTS

Solomon Islands recorded a current account deficit of approximately 6.8% of GDP in 2024, driven by the structural merchandise trade deficit of approximately 24% of GDP, partially offset by services credits (EEZ fishing access fees, USD 38 million) and official transfers (donor grants and technical assistance). Logging exports of approximately USD 165 million and tuna exports of USD 45 million covered less than 40% of the merchandise import bill (approximately USD 540 million), with fuel (26% of imports), food (22%), and manufactured goods (31%) as the largest import categories. Remittances are a small but growing external inflow at approximately USD 48 million in 2024 (2.8% of GDP), reflecting the early-stage participation of Solomon Islanders in the PALM Scheme (approximately 3,200 workers in Australia in 2024).

OUTLOOK

Solomon Islands faces a challenging medium-term outlook as logging revenues decline and the economy needs to transition toward sustainable growth drivers. Growth of 2.5–3.5% per annum through 2026–2027 is feasible, anchored by donor-financed infrastructure, fisheries sector development, and gradual PALM Scheme expansion. The principal structural risk is the exhaustion of commercially viable logging within 10–15 years, which would eliminate approximately 20% of government revenue and 30% of export earnings without a replacement sector. Climate vulnerability — particularly from cyclones and flooding in the low-lying provinces — adds to reconstruction financing pressure. ADB's country partnership strategy for Solomon Islands 2024–2028 prioritises rural connectivity, fisheries infrastructure, and economic diversification as medium-term reform anchors.`,

VAN: `OVERVIEW OF THE ECONOMY & CURRENT DEVELOPMENTS

Vanuatu's economy is estimated to have grown 2.2% in 2024, recovering from a contraction of -0.8% in the cyclone-affected year of 2023, when Tropical Cyclone Judy (Category 4, March 2023) caused damage estimated at 23% of GDP across the islands of Efate, Santo, and Malekula. The 2024 recovery was supported by reconstruction activity funded by ADB (USD 25 million emergency loan), World Bank, and Australian and New Zealand emergency grants, alongside a partial rebound in tourism from the cyclone trough. Tourist arrivals reached 142,000 in 2024, recovering to approximately 78% of the pre-cyclone level of 183,000 recorded in 2022. The ADB projects growth of 3.1% in 2025 and 3.8% in 2026 as the reconstruction impulse peaks and tourism approaches full capacity recovery, contingent on no further major natural disaster events.

Consumer price inflation, as measured by the Vanuatu National Statistics Office (VNSO) CPI, moderated to 3.6% YOY in Q3 2024 from a post-cyclone peak of 6.8% in 2023 and 5.2% in 2022, as global commodity prices eased and reconstruction-related supply bottlenecks resolved. Food prices — weighted at 38% of the CPI basket — rose 4.1% YOY in Q3 2024, driven by continued imported food price pressures and disruptions to local agricultural production in cyclone-affected areas. The Reserve Bank of Vanuatu (RBV) does not maintain a formal inflation target but monitors CPI and external reserve adequacy as primary policy indicators. GDP per capita stood at approximately USD 3,080 in 2024, below the pre-cyclone level of USD 3,340 in 2021, with recovery uneven between the urban economy of Port Vila and rural outer islands where subsistence agriculture and copra production dominate.

Vanuatu's economy is anchored by three revenue pillars: tourism and hospitality (18% of GDP in a normal year, currently recovering from the cyclone trough); the Citizenship-by-Investment (CBI) Programme — the Development Support Programme (DSP) — which generated approximately USD 180 million in 2024 (approximately 17% of GDP) through passport sales primarily to Chinese and Middle Eastern investors; and agriculture (copra, kava, cocoa, beef) contributing approximately 20% of GDP. The CBI programme has been a significant and volatile fiscal stabiliser, but faces international scrutiny regarding transparency and potential suspension of EU visa-free access (a key selling point to investors), creating a major fiscal risk. Kava exports, primarily to Australia and New Zealand, generated approximately USD 32 million in 2024, making Vanuatu the world's third-largest kava exporter.

MONETARY POLICY & FINANCIAL SECTOR

The Reserve Bank of Vanuatu (RBV) maintains monetary policy through reserve money management, open market operations, and prudential regulation of the commercial banking system. The RBV Reference Rate has been held at 3.0% since 2020, maintaining accommodative conditions to support post-cyclone recovery. The Vanuatu vatu (VUV) is pegged to a currency basket (EUR 30%, USD 30%, AUD 20%, JPY 10%, NZD 10%), providing exchange rate stability for the import-dependent economy and tourism receipts denominated primarily in AUD and USD. The basket peg has been maintained without realignment since 2011.

Private sector credit expanded 6.8% YOY in December 2024, up from 3.2% in 2023, driven by tourism-sector reconstruction loans, housing credit, and working capital financing for businesses recovering from cyclone disruption. The commercial banking system — comprising ANZ Vanuatu, BSP Vanuatu, Bred Bank Vanuatu, and National Bank of Vanuatu — held total assets of approximately VUV 185 billion (approximately USD 1.55 billion) at end-2024. The system NPL ratio stood at 6.4% at end-2024, elevated from a pre-cyclone level of 4.1% in 2021, reflecting stressed conditions in the tourism and agriculture sectors. RBV foreign reserves were USD 438 million at end-2024 (8.6 months of import cover), bolstered by CBI Programme inflows and Australian and New Zealand emergency grant receipts.

FISCAL POLICY & PUBLIC DEBT

Vanuatu's fiscal position has been characterised by significant volatility tied to CBI Programme revenue, which can fluctuate by 5–10% of GDP year to year depending on global investor demand and programme competitiveness. The fiscal deficit is estimated at 5.3% of GDP in 2024, including reconstruction expenditure that elevated the capital budget to approximately 28% of total expenditure. Total revenue (including CBI receipts) was approximately VUV 52 billion (38% of GDP), with CBI revenues (USD 180 million) representing 44% of total government revenue. Tax revenue (VAT at 12.5%, customs duties, and stamp duties) contributed 41% of total collections, while non-tax revenues (port fees, fishing licences) added 15%. Expenditure pressures include public sector wages (32% of recurrent expenditure), disaster reconstruction (ADB loan counterpart funding and government contribution), and rising debt service.

Public debt reached approximately 48% of GDP at end-2024, elevated from 33% pre-pandemic and reflecting post-COVID emergency borrowing and cyclone reconstruction financing. External debt comprises 71% of total, with ADB (29%), World Bank (22%), China Exim Bank (18%), and other bilateral creditors (31%) as the main lenders. The ADB emergency loan of USD 25 million approved in 2023 and disbursed in 2024 was the largest single external financing inflow. The IMF's 2024 DSA maintained Vanuatu at moderate risk of debt distress, noting that the CBI programme provides an unusual revenue buffer but creates fiscal vulnerability to programme suspension or revenue shortfalls.

BALANCE OF PAYMENTS

Vanuatu's current account recorded a deficit of approximately 9.8% of GDP in 2024, narrowing from 14.2% in 2023 as reconstruction import demand moderated and tourism receipts recovered. The merchandise trade deficit (approximately 32% of GDP) reflects near-total dependence on imported fuel, food, and manufactured goods, partially offset by kava (USD 32 million), copra (USD 12 million), and beef (USD 8 million) exports. Tourism receipts of approximately USD 165 million were the largest services credit, recovering toward the pre-cyclone level of USD 210 million in 2022. CBI Programme financial inflows (reported on the financial account) provided a significant capital account offset, contributing to the maintenance of adequate foreign reserves.

Gross international reserves of USD 438 million (8.6 months import cover) are robust and well above the RBV's 4-month minimum threshold. The vatu peg has been maintained without adjustment. FDI inflows of approximately USD 35 million in 2024 were concentrated in hotel reconstruction and expansion in Port Vila and Luganville, primarily from Australian and New Zealand investors.

OUTLOOK

Vanuatu's growth outlook of 3.0–4.0% per annum through 2026–2027 hinges on the continued tourism recovery and the stability of CBI Programme revenues. The dominant tail risk is a further major cyclone event — Vanuatu averages a Category 3+ cyclone every 3–5 years — which could cause reconstruction costs exceeding 20% of GDP and disrupt tourism for multiple years. The potential suspension of EU visa-free access for CBI programme holders would materially reduce programme attractiveness and could remove 10–15% of GDP from government revenues with limited short-term replacement options. ADB's Vanuatu Country Operations Business Plan 2024–2026 prioritises climate-resilient infrastructure, energy transition to renewables (targeting 100% renewable electricity by 2030), and skills development as strategic investment priorities.`,
}

// Normalise country name input → lookup key
export function matchCountry(input: string): string | null {
  const s = input.toLowerCase().trim()
  if (s.includes('papua') || s.includes('png') || s === 'new guinea') return 'PNG'
  if (s.includes('fiji') || s.includes('fij')) return 'FIJ'
  if (s.includes('tonga') || s.includes('ton')) return 'TON'
  if (s.includes('samoa') && !s.includes('american')) return 'SAM'
  if (s.includes('solomon') || s.includes('sol')) return 'SOL'
  if (s.includes('vanuatu') || s.includes('van')) return 'VAN'
  return null
}
